modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="heros_revived"
version="1.0.0"
displayName="Heros_Revived "
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="joshu, MCreator"

[[dependencies.heros_revived]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



